language: python

notifications:
  email: false

env:
  matrix:
    # Ubuntu 14.04 versions
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.6"
  global:
    - DISTRIB="conda"

install:
    - source build_tools/install.sh

before_script:
    - make clean

script:
    - python build_tools/show-python-packages-versions.py
    - make test
